version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: on-failure
    depends_on:
      - server
      - openai_backend
    networks:
      - backend_network

  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    environment:
      - OPEN_API_KEY=${OPEN_API_KEY}
      - FLASK_ENV=development
    restart: on-failure
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


  openai_backend:
    build: ./openai_backend
    ports:
      - "6000:6000"
    env_file:
      - ./openai_backend/.env
    environment:
      - OPEN_API_KEY=${OPEN_API_KEY}
    restart: on-failure
    networks:
      - backend_network

  database:
    build: ./database
    ports:
      - "5001:5001"


networks:
  backend_network:
    driver: bridge
